name: Server

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run
        run: |
          python3 daima.py "${{ secrets.APIKEY }}:${{ secrets.FRPID }}"
